- name: Setup Docker
  hosts: localhost
  connection: local 
  gather_facts: true
  become: true
  vars:
    # docker defaults
    docker_edition: 'ce'
    docker_package_state: present
    docker_service_manage: false
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present

    docker_users:
      - "{{ lookup('env', 'USER') }}"
  roles:
    - role: geerlingguy.docker